name: Metrics
on:
  schedule:
    - cron: "0 * * * *" # cada hora
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: ismaelmarot
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Argentina/Buenos_Aires
          plugin_languages: yes
          plugin_languages_ignored: cython, powershell
          plugin_languages_details: bytes-size, percentage
          plugin_dependencies: yes
